spring.datasource.url=jdbc:postgresql://localhost:5432/employeeAPC2425
spring.datasource.username=postgres
spring.datasource.password=postgre
spring.datasource.driver-class-name=org.postgresql.Driver
spring.application.name=springBoot
spring.data.rest.base-path=/api-rest